update pkg

diff --git a/etc/skel/.local/bin/install-bauh-appimage b/etc/skel/.local/bin/install-bauh-appimage
--- a/etc/skel/.local/bin/install-bauh-appimage
+++ b/etc/skel/.local/bin/install-bauh-appimage
@@ -22,7 +22,10 @@
 #    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
 #############################################################################################################################################################################
 
-set -x
+
+# -- Exit on errors.
+
+set -eu
 
 
 # -- Functions
@@ -89,8 +92,7 @@ notify-send -a "System Message" -i "appimage-cli-manager" "Desktop launcher for 
 # -- Clean up the install script if Bauh was installed successfully.
 
 if [ -f "$APPIMAGE_PATH" ]; then
-    rm "$HOME/.local/bin/install-bauh-appimage"
-    rm "$HOME/.local/share/applications/install.bauh.desktop"
+    rm -f "$HOME/.local/bin/install-bauh-appimage"
 fi
 
 exit
diff --git a/etc/skel/.local/bin/install-hgl-flatpak b/etc/skel/.local/bin/install-hgl-flatpak
--- a/etc/skel/.local/bin/install-hgl-flatpak
+++ b/etc/skel/.local/bin/install-hgl-flatpak
@@ -22,7 +22,10 @@
 #    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
 #############################################################################################################################################################################
 
-set -x
+
+# -- Exit on errors.
+
+set -eu
 
 
 # -- Add flathub.
@@ -55,7 +58,6 @@ flatpak install -y --user "runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt
 
 if flatpak list --app --columns=application | grep -q "$FPK_APP"; then
     rm "$HOME/.local/bin/install-hgl-flatpak"
-    rm "$HOME/.local/share/applications/install.hgl.desktop"
 fi
 
 notify-send -a "System Message" -i "heroic" "Launching Heroic Games Launcher."
diff --git a/etc/skel/.local/bin/install-itch-io b/etc/skel/.local/bin/install-itch-io
--- a/etc/skel/.local/bin/install-itch-io
+++ b/etc/skel/.local/bin/install-itch-io
@@ -22,7 +22,10 @@
 #    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
 #############################################################################################################################################################################
 
-set -x
+
+# -- Exit on errors.
+
+set -eu
 
 
 # -- Download setup file.
@@ -47,8 +50,6 @@ if [ -d "$HOME/.itch" ];
     then
          rm "$HOME/.local/bin/itch-setup"
          rm "$HOME/.local/bin/install-itch-io"
-         rm "$HOME/.local/share/applications/install.itch.io.desktop"
 fi
-
 
 exit
diff --git a/etc/skel/.local/bin/install-libreoffice-appimage b/etc/skel/.local/bin/install-libreoffice-appimage
--- a/etc/skel/.local/bin/install-libreoffice-appimage
+++ b/etc/skel/.local/bin/install-libreoffice-appimage
@@ -22,7 +22,10 @@
 #    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
 #############################################################################################################################################################################
 
-set -x
+
+# -- Exit on errors.
+
+set -eu
 
 
 # -- Functions
@@ -67,7 +70,6 @@ notify-send -a "System Message" -i "libreoffice-startcenter" "Installation compl
 
 if [ -f "$HOME/Applications/LibreOffice-fresh.standard-x86_64.AppImage" ]; then
     rm "$HOME/.local/bin/install-libreoffice-appimage"
-    rm "$HOME/.local/share/applications/install.libreoffice.desktop"
 fi
 
 exit
