update pkg

diff --git a/usr/bin/autostart-xdg-portals b/usr/bin/autostart-xdg-portals
--- a/usr/bin/autostart-xdg-portals
+++ b/usr/bin/autostart-xdg-portals
@@ -28,33 +28,56 @@
 set -eu
 
 
-# -- Brings up the Hyprland backend first, then the main portal, and (if present) the document/permission helpers.
+# -- Write to log.
 
-[ -n "${DBUS_SESSION_BUS_ADDRESS:-}" ] || { command -v dbus-launch >/dev/null && eval "$(dbus-launch --sh-syntax)"; }
+logger -t autostart-xdg-portals "Restarting XDG portals"
 
-BIN_HYPR="$(command -v xdg-desktop-portal-hyprland || echo /usr/lib/xdg-desktop-portal-hyprland)"
-BIN_PORTAL="$(command -v xdg-desktop-portal || echo /usr/libexec/xdg-desktop-portal)"
-BIN_DOC="/usr/libexec/xdg-document-portal"
-BIN_PERM="/usr/libexec/xdg-permission-store"
 
-if ! pgrep -f -u "$USER" '(^|/)xdg-desktop-portal-hyprland(\s|$)' >/dev/null; then
-  "$BIN_HYPR" &
+# -- Kill portal process if they're running.
+
+killall xdg-desktop-portal xdg-desktop-portal-kde xdg-desktop-portal-hyprland xdg-desktop-portal-gnome xdg-desktop-portal-wlr 2>/dev/null || true
+
+
+# -- Start portal processes.
+
+/usr/lib/xdg-desktop-portal-hyprland &
+sleep 0.2
+if pgrep -f '(^|/)xdg-desktop-portal-hyprland(\s|$)' >/dev/null; then
+  logger -t autostart-xdg-portals "Started xdg-desktop-portal-hyprland"
+else
+  logger -t autostart-xdg-portals "Failed to start xdg-desktop-portal-hyprland"
 fi
 
+/usr/lib/x86_64-linux-gnu/libexec/xdg-desktop-portal-kde &
+sleep 0.2
+if pgrep -f '(^|/)xdg-desktop-portal-kde(\s|$)' >/dev/null; then
+  logger -t autostart-xdg-portals "Started xdg-desktop-portal-kde"
+else
+  logger -t autostart-xdg-portals "Failed to start xdg-desktop-portal-kde"
+fi
+
+G_MESSAGES_DEBUG=all /usr/libexec/xdg-desktop-portal -r 2> >(logger -t autostart-xdg-portals -p user.err) &
 sleep 1
-
-if ! pgrep -f -u "$USER" '(^|/)xdg-desktop-portal(\s|$)' >/dev/null; then
-  "$BIN_PORTAL" &
+if pgrep -f '(^|/)xdg-desktop-portal(\s|$)' >/dev/null; then
+  logger -t autostart-xdg-portals "Started main xdg-desktop-portal"
+else
+  logger -t autostart-xdg-portals "Failed to start main xdg-desktop-portal"
 fi
 
-if [ -x "$BIN_DOC" ]; then
-  if ! pgrep -f -u "$USER" '(^|/)xdg-document-portal(\s|$)' >/dev/null; then
-    "$BIN_DOC" &
-  fi
+/usr/libexec/xdg-document-portal &
+sleep 0.2
+if pgrep -f '(^|/)xdg-document-portal(\s|$)' >/dev/null; then
+  logger -t autostart-xdg-portals "Started xdg-document-portal"
+else
+  logger -t autostart-xdg-portals "Failed to start xdg-document-portal"
 fi
 
-if [ -x "$BIN_PERM" ]; then
-  if ! pgrep -f -u "$USER" '(^|/)xdg-permission-store(\s|$)' >/dev/null; then
-    "$BIN_PERM" &
-  fi
+/usr/libexec/xdg-permission-store &
+sleep 0.2
+if pgrep -f '(^|/)xdg-permission-store(\s|$)' >/dev/null; then
+  logger -t autostart-xdg-portals "Started xdg-permission-store"
+else
+  logger -t autostart-xdg-portals "Failed to start xdg-permission-store"
 fi
+
+logger -t autostart-xdg-portals "XDG portal startup complete"
